services:
  app:
    container_name: forma_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
